import json
from time import time
from typing import Optional, Any, Dict, List, Union, Sequence
from pydantic import BaseModel, ConfigDict, Field, field_validator
from agentica.media import AudioResponse
from agentica.utils.log import logger


# Marker inserted by the prompt builder (agentica/agent/prompts.py) at the
# boundary between the stable system-prompt prefix and its volatile tail
# (workspace memory / learned experiences / session summary / date). Everything
# after the marker can change between turns; the model layer splits the system
# content here so only the stable prefix carries a prompt-cache breakpoint and
# churn in the tail never invalidates the big cached tools+system prefix.
VOLATILE_SYSTEM_MARKER = "<!-- agentica:volatile -->"


def strip_volatile_marker(role: str, content: Any) -> Any:
    """Remove ``VOLATILE_SYSTEM_MARKER`` from a system message's string content.

    The marker only exists to drive the cache split in providers that implement
    Anthropic-style prompt caching (the OpenAI-compatible and Claude paths).
    Providers without that split must never see it — call this when formatting
    messages for them.
    """
    if role == "system" and isinstance(content, str) and VOLATILE_SYSTEM_MARKER in content:
        return content.replace(VOLATILE_SYSTEM_MARKER, "")
    return content


class MessageReferences(BaseModel):
    """The references added to user message for RAG"""

    # The query used to retrieve the references.
    query: str
    # References (from the vector database or function calls)
    references: Optional[List[Dict[str, Any]]] = None
    # Time taken to retrieve the references.
    time: Optional[float] = None


class Message(BaseModel):
    """Message sent to the Model"""

    # The role of the message author.
    # One of system, user, assistant, or tool.
    role: str

    VALID_ROLES: frozenset = frozenset({"system", "user", "assistant", "tool"})

    @field_validator("role")
    @classmethod
    def validate_role(cls, v: str) -> str:
        _valid = frozenset({"system", "user", "assistant", "tool"})
        if v not in _valid:
            raise ValueError(
                f"Invalid message role '{v}'. Must be one of: {sorted(_valid)}"
            )
        return v
    # The contents of the message. content is required for all messages,
    # and may be null for assistant messages with function calls.
    content: Optional[Union[List[Any], str]] = None
    # An optional name for the participant.
    # Provides the model information to differentiate between participants of the same role.
    name: Optional[str] = None
    # Tool call that this message is responding to.
    tool_call_id: Optional[str] = None
    # The tool calls generated by the model, such as function calls.
    tool_calls: Optional[List[Dict[str, Any]]] = None

    # Additional modalities
    audio: Optional[Any] = None
    images: Optional[Sequence[Any]] = None
    videos: Optional[Sequence[Any]] = None

    # Output from the models
    audio_output: Optional[AudioResponse] = None

    # The thinking content from the model
    thinking: Optional[str] = None
    redacted_thinking: Optional[str] = None

    # Data from the provider we might need on subsequent messages
    provider_data: Optional[Dict[str, Any]] = None

    # Opaque provider-native compacted context. Other providers must ignore it
    # and continue from the portable role/content transcript.
    provider_checkpoint: Optional[Dict[str, Any]] = None

    # --- Provider fields that may be sent back to compatible Model APIs ---
    # OpenAI-compatible reasoning traces. DeepSeek requires this on later turns
    # when an assistant message with tool calls is replayed.
    reasoning_content: Optional[str] = None
    # -*- Attributes not sent to the model
    # Why the model stopped generating this message (stop | length | tool_calls
    # | content_filter | ...). Kept for audit/replay fidelity; not sent to the API.
    finish_reason: Optional[str] = None
    # The name of the tool called
    tool_name: Optional[str] = Field(default=None, alias="tool_call_name")
    # Arguments passed to the tool
    tool_args: Optional[Any] = Field(default=None, alias="tool_call_arguments")
    # The error of the tool call
    tool_call_error: Optional[bool] = None
    # If True, the agent will stop executing after this tool call.
    stop_after_tool_call: bool = False

    # Metrics for the message. This is not sent to the Model API.
    metrics: Dict[str, Any] = Field(default_factory=dict)

    # The references added to the message for RAG
    references: Optional[MessageReferences] = None

    # Compressed content for tool results (used by CompressionManager)
    compressed_content: Optional[str] = None

    # Set by evict_tool_results() once every result this message carries is a
    # placeholder, so later passes can skip it outright. A message is the unit
    # here, but a result is not: an Anthropic round packs several tool_result
    # blocks into one user message and is only done when the last one goes.
    _evicted: bool = False

    # The Unix timestamp the message was created.
    created_at: int = Field(default_factory=lambda: int(time()))

    model_config = ConfigDict(extra="allow", populate_by_name=True, arbitrary_types_allowed=True)

    def get_content_string(self) -> str:
        """Returns the content as a string."""
        if isinstance(self.content, str):
            return self.content
        if isinstance(self.content, list):
            if len(self.content) > 0 and isinstance(self.content[0], dict) and "text" in self.content[0]:
                return self.content[0].get("text", "")
            else:
                return json.dumps(self.content, ensure_ascii=False)
        return ""

    def get_content(self, use_compressed_content: bool = False) -> Optional[Union[List[Any], str]]:
        """
        Returns the content, optionally using compressed content if available.
        
        Args:
            use_compressed_content: If True and compressed_content exists, return it instead
        
        Returns:
            The message content (compressed if requested and available)
        """
        if use_compressed_content and self.compressed_content is not None:
            return self.compressed_content
        return self.content

    def to_model_dict(self) -> Dict[str, Any]:
        """Serialize only fields intended for provider API requests."""
        _dict = self.model_dump(
            exclude_none=True,
            include={"role", "content", "audio", "name", "tool_call_id", "tool_calls", "reasoning_content"},
        )
        # Manually add the content field even if it is None
        if self.content is None:
            _dict["content"] = None
        return _dict

    def to_replay_dict(self) -> Dict[str, Any]:
        """Serialize provider/audit metadata needed for faithful session replay."""
        _dict = self.model_dump(
            exclude_none=True,
            include={
                "role", "content", "audio", "name", "tool_call_id", "tool_calls",
                "reasoning_content", "finish_reason", "provider_data", "metrics",
                "provider_checkpoint",
                "thinking", "redacted_thinking",
            },
        )
        if self.content is None:
            _dict["content"] = None
        return _dict

    def log(self, level: Optional[str] = None):
        """Log the message to the console

        @param level: The level to log the message at. One of debug, info, warning, or error.
            Defaults to debug.
        """
        level = level or "debug"
        level = level.lower()
        if level == "debug":
            _logger = logger.debug
        elif level == "info":
            _logger = logger.info
        elif level == "warning":
            _logger = logger.warning
        elif level == "error":
            _logger = logger.error
        else:
            _logger = logger.debug

        _logger(f"[{self.role}] {self.to_model_dict()}")

    def content_is_valid(self) -> bool:
        """Check if the message content is valid."""

        return self.content is not None and len(self.content) > 0


class SystemMessage(Message):
    """System message to the model
    
    Supports shorthand: SystemMessage("You are helpful") instead of SystemMessage(content="You are helpful")
    """
    role: str = "system"

    def __init__(self, content: Optional[Union[List[Any], str]] = None, **kwargs):
        """Initialize SystemMessage with optional positional content argument.
        
        Args:
            content: The message content (can be passed as positional argument)
            **kwargs: Additional keyword arguments passed to Message
        """
        super().__init__(content=content, **kwargs)


class UserMessage(Message):
    """User message to the model
    
    Supports shorthand: UserMessage("hello") instead of UserMessage(content="hello")
    """
    role: str = "user"

    def __init__(self, content: Optional[Union[List[Any], str]] = None, **kwargs):
        """Initialize UserMessage with optional positional content argument.
        
        Args:
            content: The message content (can be passed as positional argument)
            **kwargs: Additional keyword arguments passed to Message
        """
        super().__init__(content=content, **kwargs)


class AssistantMessage(Message):
    """Assistant message from the model"""
    role: str = "assistant"

    def __init__(self, content: Optional[Union[List[Any], str]] = None, **kwargs):
        super().__init__(content=content, **kwargs)


class ToolMessage(Message):
    """Tool/Function message"""
    role: str = "tool"
