# -*- coding: utf-8 -*-
"""
@author:XuMing(xuming624@qq.com)
@description: Single-source registry for Agentica's top-level public API.
"""

PROVIDER_ALIAS_EXPORTS = [
    "DeepSeekChat", "DeepSeek", "MoonshotChat", "Moonshot",
    "ArkChat", "Ark", "TogetherChat", "Together",
    "GrokChat", "Grok", "YiChat", "Yi", "QwenChat", "Qwen",
    "ZhipuAIChat", "ZhipuAI",
    "NvidiaChat", "SambanovaChat", "OpenRouterChat",
    "FireworksChat", "InternLMChat",
    "PROVIDER_FACTORIES",
    "register_provider", "unregister_provider", "get_provider_factory",
    "list_providers", "create_provider",
    "AuxiliaryModelRouter",
    "scrub_reasoning", "contains_reasoning_leak",
    "sanitize_assistant_content_for_history",
    "run_doctor", "DoctorReport", "DoctorCheck",
]

LAZY_IMPORTS = {
    # database implementations
    "SqliteDb": "agentica.db.sqlite",
    "PostgresDb": "agentica.db.postgres",
    "InMemoryDb": "agentica.db.memory",
    "JsonDb": "agentica.db.json",
    "MysqlDb": "agentica.db.mysql",
    "RedisDb": "agentica.db.redis",
    # model core (pulls in openai SDK; OpenAIChat itself is now eager)
    "Model": "agentica.model.base",
    "ModelResponse": "agentica.model.response",
    "FileType": "agentica.model.response",
    "AzureOpenAIChat": "agentica.model.azure.openai_chat",
    # model providers (heavy dependencies)
    "LiteLLMChat": "agentica.model.litellm.chat",
    "LiteLLM": "agentica.model.litellm.chat",
    "KimiChat": "agentica.model.kimi.chat",
    "Claude": "agentica.model.anthropic.claude",
    "Ollama": "agentica.model.ollama.chat",
    # knowledge
    "Knowledge": "agentica.knowledge.base",
    "LlamaIndexKnowledge": "agentica.knowledge.llamaindex_knowledge",
    "LangChainKnowledge": "agentica.knowledge.langchain_knowledge",
    # vectordb
    "SearchType": "agentica.vectordb.base",
    "Distance": "agentica.vectordb.base",
    "VectorDb": "agentica.vectordb.base",
    "InMemoryVectorDb": "agentica.vectordb.memory_vectordb",
    # embeddings
    "Embedding": "agentica.embedding.base",
    "OpenAIEmbedding": "agentica.embedding.openai",
    "AzureOpenAIEmbedding": "agentica.embedding.azure_openai",
    "HashEmbedding": "agentica.embedding.hash",
    "OllamaEmbedding": "agentica.embedding.ollama",
    "TogetherEmbedding": "agentica.embedding.together",
    "FireworksEmbedding": "agentica.embedding.fireworks",
    "ZhipuAIEmbedding": "agentica.embedding.zhipuai",
    "HttpEmbedding": "agentica.embedding.http",
    "JinaEmbedding": "agentica.embedding.jina",
    "GeminiEmbedding": "agentica.embedding.gemini",
    "HuggingfaceEmbedding": "agentica.embedding.huggingface",
    "MulanAIEmbedding": "agentica.embedding.mulanai",
    # rerank
    "Rerank": "agentica.rerank.base",
    "JinaRerank": "agentica.rerank.jina",
    "ZhipuAIRerank": "agentica.rerank.zhipuai",
    # skills
    "Skill": "agentica.skills",
    "SkillRegistry": "agentica.skills",
    "SkillLoader": "agentica.skills",
    "get_skill_registry": "agentica.skills",
    "reset_skill_registry": "agentica.skills",
    "load_skills": "agentica.skills",
    "get_available_skills": "agentica.skills",
    "register_skill": "agentica.skills",
    "register_skills": "agentica.skills",
    "list_skill_files": "agentica.skills",
    "read_skill_file": "agentica.skills",
    # guardrails (agent-level)
    "InputGuardrail": "agentica.guardrails",
    "OutputGuardrail": "agentica.guardrails",
    "InputGuardrailResult": "agentica.guardrails",
    "OutputGuardrailResult": "agentica.guardrails",
    "input_guardrail": "agentica.guardrails",
    "output_guardrail": "agentica.guardrails",
    "InputGuardrailTripwireTriggered": "agentica.guardrails",
    "OutputGuardrailTripwireTriggered": "agentica.guardrails",
    # guardrails (tool-level)
    "ToolGuardrailFunctionOutput": "agentica.guardrails",
    "ToolInputGuardrail": "agentica.guardrails",
    "ToolOutputGuardrail": "agentica.guardrails",
    "ToolInputGuardrailData": "agentica.guardrails",
    "ToolOutputGuardrailData": "agentica.guardrails",
    "ToolContext": "agentica.guardrails",
    "tool_input_guardrail": "agentica.guardrails",
    "tool_output_guardrail": "agentica.guardrails",
    "ToolInputGuardrailTripwireTriggered": "agentica.guardrails",
    "ToolOutputGuardrailTripwireTriggered": "agentica.guardrails",
    "ToolGuardrailTripwireTriggered": "agentica.guardrails",
    "run_input_guardrails": "agentica.guardrails",
    "run_output_guardrails": "agentica.guardrails",
    "run_tool_input_guardrails": "agentica.guardrails",
    "run_tool_output_guardrails": "agentica.guardrails",
    # LSP edit-time diagnostics (pulls subprocess/LSP machinery; keep lazy)
    "LspDiagnosticsChecker": "agentica.lsp_diagnostics",
    "Diagnostic": "agentica.lsp_diagnostics",
    "format_diagnostics": "agentica.lsp_diagnostics",
    # tools (external dependencies)
    "CronTool": "agentica.tools.cron_tool",
    "check_command_safety": "agentica.tools.safety",
    "redact_sensitive_text": "agentica.tools.safety",
    "set_interrupt": "agentica.tools.interrupt",
    "is_interrupted": "agentica.tools.interrupt",
    "tool_error": "agentica.tools.helpers",
    "tool_result": "agentica.tools.helpers",
    "SearchSerperTool": "agentica.tools.search_serper_tool",
    "BaiduSearchTool": "agentica.tools.baidu_search_tool",
    "ImageAnalysisTool": "agentica.tools.image_analysis_tool",
    "DalleTool": "agentica.tools.dalle_tool",
    "HackerNewsTool": "agentica.tools.hackernews_tool",
    "JinaTool": "agentica.tools.jina_tool",
    "ShellTool": "agentica.tools.shell_tool",
    "SkillTool": "agentica.tools.skill_tool",
    "WeatherTool": "agentica.tools.weather_tool",
    "CodeTool": "agentica.tools.code_tool",
    "PatchTool": "agentica.tools.patch_tool",
    # built-in tools — moved to eager imports in __init__.py.
    # Only the helper factory stays lazy (avoids importing all tool modules at startup).
    "get_builtin_tools": "agentica.tools.buildin_tools",
    # subagent system
    "SubagentType": "agentica.subagent",
    # swarm system
    "Swarm": "agentica.swarm",
    "SwarmResult": "agentica.swarm",
    "SubagentConfig": "agentica.subagent",
    "SubagentRun": "agentica.subagent",
    "SubagentRegistry": "agentica.subagent",
    "get_subagent_config": "agentica.subagent",
    "get_available_subagent_types": "agentica.subagent",
    "register_custom_subagent": "agentica.subagent",
    "unregister_custom_subagent": "agentica.subagent",
    "get_custom_subagent_configs": "agentica.subagent",
    # acp system
    "ACPServer": "agentica.acp",
    "ACPTool": "agentica.acp",
    "ACPToolCall": "agentica.acp",
    "ACPToolResult": "agentica.acp",
    "ACPRequest": "agentica.acp",
    "ACPResponse": "agentica.acp",
    "ACPErrorCode": "agentica.acp",
    "ACPMethod": "agentica.acp",
    "SessionManager": "agentica.acp",
    "ACPSession": "agentica.acp",
    "SessionStatus": "agentica.acp",
    # human-in-the-loop tool
    "AskUserQuestionTool": "agentica.tools.user_input_tool",
    "AskUserQuestionRequired": "agentica.tools.user_input_tool",
    # mcp
    "MCPConfig": "agentica.mcp.config",
    "McpTool": "agentica.tools.mcp_tool",
    "CompositeMultiMcpTool": "agentica.tools.mcp_tool",
}

LAZY_ATTR_OVERRIDES = {
    "LiteLLM": "LiteLLMChat",
}

EAGER_PUBLIC_EXPORTS = [
    "__version__",
    "AGENTICA_HOME", "AGENTICA_DOTENV_PATH", "AGENTICA_LOG_LEVEL",
    "AGENTICA_LOG_FILE", "AGENTICA_WORKSPACE_DIR", "AGENTICA_PROJECTS_DIR",
    "AGENTICA_CRON_DIR",
    "set_log_level_to_debug", "set_log_level_to_info", "logger",
    "write_audio_to_file",
    "Message", "MessageReferences", "UserMessage", "AssistantMessage",
    "SystemMessage", "ToolMessage", "Media", "Video", "Audio", "Image",
    "Usage", "RequestUsage", "TokenDetails",
    "OpenAIChat",
    "BuiltinFileTool", "BuiltinExecuteTool", "BuiltinFetchUrlTool",
    "BuiltinWebSearchTool", "BuiltinTodoTool", "BuiltinTaskTool", "BuiltinMemoryTool",
    "AgentRun", "SessionSummary", "MemorySummarizer", "WorkingMemory",
    "MemoryType", "MemoryEntry",
    "WorkflowRun", "WorkflowMemory",
    "BaseDb", "SessionRow", "MemoryRow", "MetricsRow",
    "RunResponse", "RunEvent", "RunBreakReason", "RunResponseExtraData", "ToolCallInfo", "pprint_run_response",
    "RunContext", "RunSource", "RunStatus", "TaskAnchor",
    "RunEventRecord", "RunEventType",
    "LearningReport", "LearningStatus", "write_learning_report",
    "Document",
    "Tool", "ModelTool", "Function", "FunctionCall", "tool",
    "CompressionManager",
    "CheckpointManager", "Checkpoint", "CheckpointFile",
    "count_tokens", "count_text_tokens", "count_image_tokens",
    "count_message_tokens", "count_tool_tokens",
    "Agent", "AgentCancelledError",
    "PromptConfig", "ToolConfig", "WorkspaceMemoryConfig", "HistoryConfig", "SandboxConfig",
    "ToolRuntimeConfig", "SkillRuntimeConfig", "ExperienceConfig", "SkillUpgradeConfig",
    "RunConfig", "Workflow", "WorkflowSession", "AgentHooks", "RunHooks",
    "ConversationArchiveHooks", "MemoryExtractHooks", "ExperienceCaptureHooks",
    "ExperienceEventStore", "ExperienceCompiler", "CompiledExperienceStore", "SkillEvolutionManager",
    "SkillLifecycleHooks", "NoopSkillLifecycleHooks",
    "Workspace", "WorkspaceConfig",
    "Critic", "CritiqueResult", "CritiqueStyle", "RefineResult", "RefineRound",
    "SchemaCritic", "ExecCritic", "AgentCritic", "refine",
]

PUBLIC_API_ALL = [
    *EAGER_PUBLIC_EXPORTS,
    *PROVIDER_ALIAS_EXPORTS,
    *LAZY_IMPORTS.keys(),
]
