# -*- coding: utf-8 -*-
"""
@author:XuMing(xuming624@qq.com)
@description: Fan-out demo — drive MANY independent goals concurrently.

     tasks.jsonl ──read──▶ [run_goal(A), run_goal(B), run_goal(C), ...] ──▶ task_results.md

Contrast with task_dag_runner.py:
  - task_dag_runner.py : ONE goal whose work forms a DAG (parallel + serial
                         tool calls inside a single run_goal loop).
  - task_runner.py     : MANY independent goals run side-by-side. Each task is
                         its own standing goal with its own judge loop and its
                         own budget. run_goal() clones the agent internally, so
                         asyncio.gather over one agent is safe.

Input is JSONL (one task object per line) so parsing is a single json.loads —
no regex, no markdown scraping. Each line may carry its own budget, which is
the whole point: independent goals are independently configurable.

    {"task": "...", "turn_budget": 3}
    {"task": "..."}                      # budgets optional → defaults apply
"""

from __future__ import annotations

import asyncio
import json
import os
import sys
from pathlib import Path

sys.path.append(str(Path(__file__).parent.parent.parent))

from agentica import DeepAgent, DeepSeekChat

HERE = Path(__file__).parent
TASKS_FILE = HERE / "tasks.jsonl"
RESULTS_FILE = HERE / "task_results.md"

# Defaults applied when a JSONL line omits a budget. Generous safety nets —
# the judge / update_goal tool is the primary stop signal, not the budget.
DEFAULT_BUDGETS = {"turn_budget": 5, "token_budget": 60_000, "wall_clock_budget_sec": 180}


def load_tasks(filepath: Path) -> list[dict]:
    """One json.loads per non-empty line. Each dict has at least ``task``."""
    tasks: list[dict] = []
    for line in filepath.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        obj = json.loads(line)
        if obj.get("task"):
            tasks.append(obj)
    return tasks


def make_callback(index: int):
    """Per-task event_callback; tags lines with the task index so the
    interleaved output of concurrent goals stays readable."""

    def on_event(event, payload: dict) -> None:
        turns = f"{payload.get('turns_used')}/{payload.get('turn_budget')}"
        msg = payload.get("message") or payload.get("reason") or ""
        print(f"  [task {index}] turn {turns} {msg}".rstrip(), flush=True)

    return on_event


async def process_task(agent: DeepAgent, spec: dict, index: int) -> tuple[int, str, str]:
    task = spec["task"]
    # Per-task budgets: take from the JSONL line, else fall back to defaults.
    budgets = {k: spec.get(k, v) for k, v in DEFAULT_BUDGETS.items()}
    print(f"[task {index}] start (turn_budget={budgets['turn_budget']}): {task[:60]}")
    result = await agent.run_goal(task, event_callback=make_callback(index), **budgets)
    body = result.response_content.strip()[:300]
    print(f"[task {index}] done  status={result.status}  turns={result.turns_used}")
    return index, task, f"status={result.status} | turns={result.turns_used} | {body}"


def write_results(results: list[tuple[int, str, str]]) -> None:
    header = "# Task Results\n\n> Auto-generated by `task_runner.py`\n\n"
    body = "".join(f"## Task {idx}: {task}\n\n{summary}\n\n" for idx, task, summary in sorted(results))
    RESULTS_FILE.write_text(header + body, encoding="utf-8")
    print(f"Results written to {RESULTS_FILE}")


async def main() -> None:
    key = os.getenv("DEEPSEEK_API_KEY")
    if not key:
        print("Set DEEPSEEK_API_KEY env var to run this demo.")
        return

    tasks = load_tasks(TASKS_FILE)
    if not tasks:
        print(f"No tasks found in {TASKS_FILE}")
        return
    print(f"Found {len(tasks)} task(s) in {TASKS_FILE}\n")

    agent = DeepAgent(
        model=DeepSeekChat(id="deepseek-chat", api_key=key),
        instructions=(
            "Answer concisely. When done, call update_goal(status='complete', "
            "final_answer=<your full answer>). Put the complete answer in "
            "final_answer; do not add a separate closing message."
        ),
    )

    # Fan out: one independent goal per task, all running concurrently.
    results = await asyncio.gather(*[process_task(agent, spec, i) for i, spec in enumerate(tasks, 1)])
    print()
    write_results(results)


if __name__ == "__main__":
    asyncio.run(main())
